### ISSUE TITLE
import error,ImportError: cannot import name bisonToPython

### ISSUE THREAD

**Issue by arshpreetsingh** [smvv/pybison#2]
When I run bison2python from Linux terminal it returns the error:
ImportError: cannot import name bisonToPython

Same error is also produced when I use following command in the Python shell

from bison import bisonToPython

**Comment by smvv** [comment]
That's because bison2python is currently not supported. When we rewrote the implementation of pybison, we did not port the bison2python conversion tool.

We converted the bison grammar to Python code manually and over time (while developing TRS), so there was no need to support that tool. But a pull request is welcome btw!

**Comment by arshpreetsingh** [comment]
I saw there are required file present in the /src/python/convert.py, Please Guide me, I would love to Contribute!

**Comment by pkociepka** [comment]
Hello. Are you going to support bison2python script? It could be very useful for me. If there is any way to fix it, let me know.

**Comment by thisiscam** [comment]
Hi, I know it's kind of late, but I have created a PR for this
https://github.com/smvv/pybison/pull/4

**Comment by smvv** [comment]
I've merged the PR. This is resolved, right? Feel free to re-open if it is not.
